language: python

python:
  - "3.6.5"

install:
  - pip install -r requirements.txt
  - pip install pytest 

script: 
  - python -m pytest --cov-report term-missing --cov=app


after_success:
  - coveralls

cache: pip
